# Generated by Django 4.1.3 on 2022-11-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_bio_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.CharField(default='0745547755', max_length=10),
            preserve_default=False,
        ),
    ]
