# Generated by Django 4.1.3 on 2022-11-10 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField()),
                ('link', models.URLField(max_length=255)),
                ('is_public', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('SPORTS', 'Sports'), ('FINANCE', 'Finance'), ('EDUCATION', 'Education'), ('FIXED', 'Fixed')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='adverts/')),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.advert')),
            ],
        ),
    ]
