# Generated by Django 4.1.3 on 2022-11-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='adverts/'),
        ),
    ]
