# Generated by Django 4.1.3 on 2022-11-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_advert_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
