# Generated by Django 4.1.3 on 2022-11-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_tag_img_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='img_tag',
            field=models.ImageField(default='img/post1.jpg', upload_to='tags/'),
        ),
    ]
