# Generated by Django 4.1.3 on 2022-11-08 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_tag_img_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='pub_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
