# Generated by Django 4.1.3 on 2022-11-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_tag_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='content',
            field=models.CharField(default='Hello people how are you people', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='summary',
            field=models.CharField(default='Hellop people this is content', max_length=100),
            preserve_default=False,
        ),
    ]
