# Generated by Django 4.1.3 on 2022-11-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(default='img/post1.jpg', upload_to='posts/'),
        ),
    ]
