# Generated by Django 4.1.3 on 2022-11-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_post_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub_title',
            field=models.CharField(default='Hello', max_length=100),
            preserve_default=False,
        ),
    ]
