# Generated by Django 4.1.3 on 2022-11-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_post_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub_content',
            field=models.TextField(default='Beach Restoration Project Moving Forward: A $17 million beach restoration project, funded by the Mexican government, is currently underway. The project, which is expected to take about eight months to complete, will restore and augment beaches along the 7 1/2-mile stretch between Punta Cancun and Punta Nizuc.'),
            preserve_default=False,
        ),
    ]
