# Generated by Django 4.1.3 on 2022-11-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0006_postimage_alter_alert_alert_post_sub_content_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='quote',
            field=models.CharField(default='Joj job job job job bjb', max_length=100),
            preserve_default=False,
        ),
    ]
