# Generated by Django 4.1.3 on 2022-11-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0009_remove_post_tag_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='quote',
            field=models.CharField(max_length=500),
        ),
    ]
