# Generated by Django 4.1.3 on 2022-11-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0010_alter_post_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('FS', 'Featured Stories'), ('DM', 'Drama'), ('DOC', 'Documentary')], default='FS', max_length=100),
        ),
    ]
