# Generated by Django 4.1.3 on 2022-11-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0012_post_public_alter_post_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': '-pub_date', 'ordering': ['-pub_date'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
