# Generated by Django 4.1.3 on 2022-11-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0014_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True, unique_for_month='pub_date'),
        ),
    ]
