# Generated by Django 4.1.3 on 2022-11-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
