# Generated by Django 4.1.3 on 2022-11-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_alter_comment_pub_date_alter_commentreply_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': '-pub_date', 'ordering': ['-pub_date']},
        ),
        migrations.DeleteModel(
            name='CommentReply',
        ),
    ]
